server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: farm-service
          uri: lb://farm-service
          predicates:
            - Path=/api/farms/**
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/api/devices/**
        - id: alarm-service
          uri: lb://alarm-service
          predicates:
            - Path=/api/alarms/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
